apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  path: {{ .Values.namespace }}/{{ .Values.appName }}
  type: Opaque
